{
 "title": "Metricbeat - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\":\"node.keyword\"}"
   },
   {
    "name": "overlay",
    "label": "Module",
    "query": "{\"find\": \"terms\", \"field\":\"overlay.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "memory",
     "bucketAggs": [
      {
       "$$hashKey": "object:15",
       "fake": true,
       "field": "container_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:16",
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:13",
       "field": "docker_memory_usage_total",
       "id": "1",
       "inlineScript": "_value / (1024 * 1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024 * 1024)" } },
       "type": "avg"
      }
     ],
     "query": "node = $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kibana Requests & Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{term overlay.keyword}} - Requests",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kibana_status_metrics_requests_total",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "sum"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - Disconnects",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kibana_status_metrics_requests_disconnects",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "sum"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - Connections",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kibana_status_metrics_concurrent_connections",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "sum"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "alias": "{{term overlay.keyword}} - Document Count",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_indices_docs_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - Store Size (Mb)",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_indices_store_size_bytes",
       "id": "1",
       "inlineScript": "_value / (1024*1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024*1024)" } },
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - Space Available (Gb)",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_fs_summary_available_bytes",
       "id": "1",
       "inlineScript": "_value / (1024*1024*1024)",
       "meta": {},
       "settings": { "script": { "inline": "_value / (1024*1024*1024)" } },
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - JVM Collection Time Old (ms)",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_jvm_gc_collectors_old_collection_ms",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - JVM Collection Count Old",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_jvm_gc_collectors_old_collection_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - JVM Collection Time Young",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_jvm_gc_collectors_young_collection_ms",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - VM Collection Count Young",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_jvm_gc_collectors_young_collection_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Containers - Disk IO Writes Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker_diskio_write_bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Containers - Network Out Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker_network_out_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load 1m",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_load_norm_1",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "Where node = $node and event_dataset = 'system.cpu'",
     "timeField": "@timestamp"
    },
    {
     "alias": "Load 5m",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_load_norm_5",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Load 15m",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_load_norm_15",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Elasticsearch - Segments Count & Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Segments" }
   ],
   "targets": [
    {
     "alias": "{{term overlay.keyword}} - Segments",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_indices_segments_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - Segments Memory",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_indices_segments_memory_bytes",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Containers - Top 20 - Disk IO Reads Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker_diskio_read_bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Containers - Top 20 - Network In Bytes/min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "1",
        "size": "20"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker_network_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes", "label": "percentage" }
   ],
   "targets": [
    {
     "alias": "Menory Used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_memory_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Memory Actual Used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_memory_actual_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    },
    {
     "alias": "Swap Used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_memory_swap_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_memory_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ElasticSearch JVM - Memory Pools",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{term overlay.keyword}} - Old",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_jvm_mem_pools_old_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - Survivor",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_jvm_mem_pools_survivor_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term overlay.keyword}} - Young",
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elasticsearch_node_stats_jvm_mem_pools_young_used_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kafka Topic Partitions Offset Newest Change / min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kafka_topic_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kafka_partition_offset_newest",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "avg"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kafka - Consumergroups Offset Change / min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "overlay.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kafka_consumergroup_id.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kafka_consumergroup_offset",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "Where overlay = $overlay",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Network Inward",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "percentage" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system_network_in_bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "Where node = $node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}