{
 "title": "Metricbeat - Docker CPU",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"node.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Total - Per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker_cpu_total_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE node=$node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average CPU - Last 2 min",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "alias": "Average CPU",
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "docker_cpu_total_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where node=$node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU User - Per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker_cpu_user_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE node=$node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average CPU - Last 5 min",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 7 },
   "targets": [
    {
     "alias": "Average CPU",
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "docker_cpu_user_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where node=$node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Kernel - Per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker_cpu_kernel_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "WHERE node = $node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average CPU - Last 15 min",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 14 },
   "targets": [
    {
     "alias": "Average CPU",
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "docker_cpu_total_pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "Where node=$node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}