#!/usr/bin/env bash
selectedNode="${@: -1}"

executionplane-info "EXECUTING CONTROLPLANE BOOT"

.solution run boot . export $selectedNode

.solution run start . ingest $selectedNode

.solution run boot . ksqldb $selectedNode

sleep 10;

.solution run stop . ingest $selectedNode
