#!/usr/bin/env bash
selectedNode="${@: -1}"

executionplane-info "EXECUTING CONTROLPLANE REMOVE"

.solution run shutdown . schema $selectedNode
.solution run shutdown . ekg $selectedNode
.solution run shutdown . kz $selectedNode

.solution deploy down . $selectedNode
