#!/usr/bin/env bash
selectedNode="${@: -1}"

executionplane-info "EXECUTING CONTROLPLANE SHUTDOWN"

.solution run shutdown . ksqldb $selectedNode
.solution run stop . _ui $selectedNode
.solution run shutdown . export $selectedNode
