#!/usr/bin/env bash

# START CONFIGURATION
DOLLAR='$'
export VCW_MODULE_PACKAGES="\
ekg:vcwc/elastic/stacks/ekg/traefik,\
export:vcwc/streamsets,\
ingest_journal:vcwc/elastic/journalbeat,\
ksqldb:vcwc/confluent_ksqldb,\
ksqldb_dev:vcwc/confluent_ksqldb,\
kz:vcwc/confluent/kafka/kz,\
metrics_monitors:vcwc/elastic/heartbeat,\
metrics_node:vcwc/elastic/metricbeat/node,\
metrics_overlay:vcwc/elastic/metricbeat/overlay,\
schema_registry:vcwc/confluent/schema_registry"
# END CONFIGURATION

# START OTHER SETTINGS
export INGEST_JOURNAL_MODULE_HOST_JOURNALPATH="/var/log/journal"
export INGEST_JOURNAL_MODULE_KSQLDB_MEMORY_RESERVED="1024m"
export INGEST_JOURNAL_MODULE_KSQLDB_MEMORY_LIMIT="1526m"
# END OTHER SETTINGS
