#!/usr/bin/env bash

executionplane --silent docker volume create vcwc_swarm_journal__ekg_elasticsearch_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__ekg_grafana_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__ekg_nginx_config_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__export_streamsets_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__ingest_journal_journalbeat_config
	
executionplane --silent docker volume create vcwc_swarm_journal__ingest_journal_journalbeat_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__ksqldb_ksqldb_queries_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__ksqldb_dev_ksqldb_queries_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__kz_kafka_secrets_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__kz_kafka_data_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__kz_zookeeper_secrets_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__kz_zookeeper_data_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__kz_zookeeper_log_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__metrics_node_metricbeat_config
	
executionplane --silent docker volume create vcwc_swarm_journal__metrics_node_metricbeat_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__metrics_overlay_metricbeat_config
	
executionplane --silent docker volume create vcwc_swarm_journal__metrics_overlay_metricbeat_volume
	
executionplane --silent docker volume create vcwc_swarm_journal__schema_registry_schema_registry_secrets_volume
	

executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__ekg_elasticsearch_volume:/usr/share/elasticsearch/data ${VCW_REGISTRY}vcwc/controlplane.vcw console untar /source/vcwc/swarm/journal/_solution/_component/_volumes/ekg_elasticsearch_volume.tar


executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__ekg_grafana_volume:/var/lib/grafana ${VCW_REGISTRY}vcwc/controlplane.vcw console untar /source/vcwc/swarm/journal/_solution/_component/_volumes/ekg_grafana_volume.tar


executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__ekg_nginx_config_volume:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/swarm/journal/_solution/_component/_volumes/ekg_nginx_config_volume/* /vcw/pwd


executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__export_streamsets_volume:/data ${VCW_REGISTRY}vcwc/controlplane.vcw console untar /source/vcwc/swarm/journal/_solution/_component/_volumes/export_streamsets_volume.tar


executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__ingest_journal_journalbeat_config:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/swarm/journal/_solution/_component/_volumes/ingest_journal_journalbeat_config/* /vcw/pwd


executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__ksqldb_ksqldb_queries_volume:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/swarm/journal/_solution/_component/_volumes/ksqldb_ksqldb_queries_volume/* /vcw/pwd


executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__ksqldb_dev_ksqldb_queries_volume:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console untar /source/vcwc/swarm/journal/_solution/_component/_volumes/ksqldb_dev_ksqldb_queries_volume.tar


executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__metrics_node_metricbeat_config:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/swarm/journal/_solution/_component/_volumes/metrics_node_metricbeat_config/* /vcw/pwd


executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_swarm_journal__metrics_overlay_metricbeat_config:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/swarm/journal/_solution/_component/_volumes/metrics_overlay_metricbeat_config/* /vcw/pwd

