---
version: '3'
services:

# START SERVICE vcwc/nginx/rewrite
  nginx:
    image: ${VCW_REGISTRY}vcwc/nginx.base:1.19.3
    environment: ['VCW_STACK_NGINX_CONF_LOCATION=/${VCW_STACK_GLOBAL_URLPREFIX}/streamsets', 'VCW_STACK_NGINX_CONF_PROXY_PASS=${VCW_STACK_GLOBAL_STACKPREFIX}_streamsets:18630']
    command: []
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_nginx_config_volume:/vcw/pwd']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${EXPORT_UI_STREAMSETS_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${EXPORT_UI_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'

      labels: [traefik.enable=true,traefik.docker.network=${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay,
      traefik.http.services.${VCW_STACK_GLOBAL_STACKPREFIX}_nginx.loadbalancer.server.port=80,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_nginx.entrypoints=conteco,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_nginx.rule=PathPrefix("/${VCW_STACK_GLOBAL_URLPREFIX}/streamsets")]
${EXPORT_UI_STREAMSETS_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/nginx/rewrite

networks: {${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay: { external: true }, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_nginx_config_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
